name: Publish Package to npmjs
on:
  workflow_call: 
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          cache: "yarn"
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: yarn install --frozen-lockfile
      - run: yarn build

      # Publish NPM
      - run: yarn semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
