name: Publish Package to npmjs
on:
  push:
    branches: 
      - master
jobs:
  build:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          cache: "pnpm"
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build

      # Publish NPM
      - name: create and publish versions
        uses: changesets/action@v1
        id: create_and_publish_versions
        with:
          publish: pnpm release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN:  ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN:  ${{ secrets.NPM_TOKEN }}
